# Generated by Django 3.2.7 on 2021-09-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soliproducts', '0002_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
