# Generated by Django 3.2.7 on 2022-01-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soliblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Blog',
        ),
    ]
