# Generated by Django 3.2.7 on 2022-01-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
